### PR TITLE
Go implementation of PoP token library

### PR DESCRIPTION
**Pull request by klmitch**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

This pull request contains a Go implementation of the PoP token libraries, encompassing both creation and validation of PoP tokens on HTTP requests.

### Benefits

By accepting this pull request, API consumers that are implemented in Go will be able to both create and verify PoP tokens easily, without having to reimplement the logic.

### Possible Drawbacks

This is an isolated change that does not touch any other PoP token libraries contained in this repository, so there should be no drawbacks.

### Applicable Issues

None known.

### CODE REVIEW

**Comment by klmitch** [comment]
Note that this is a draft; I have not yet implemented unit tests.  I have opted to create a pull request at this time to invite critique of the provided interface.

I also have one open question, which concerns the exact implementation of the case where a given header appears in the request multiple times: the implementation I have chosen is based on a reading of RFC 9110 (see [section 5.3](https://www.rfc-editor.org/rfc/rfc9110.html#name-field-order)), but I see a competing Go implementation that opted to repeat the key in the EHTS string multiple times and simply concatenate the values with no joining string to compute the EDTS hash.  It's not clear to me which of these is the correct approach for the existing validators, or if there is another approach that is more correct for this case, and I would appreciate guidance on which algorithm to implement.

(For context, in a Go `http.Request`, the headers are stored as a map from the request header names to a list of strings.)

**Comment by klmitch** [comment]
This PR now contains full unit tests.  However, there is still the open question of the correct handling for repeated header values.  If I get some time, I intend to test this against an in-house PoP token verifier.

**Comment by klmitch** [comment]
I attempted to test this against our in-house PoP token verifier, but I found that I could change the headers with impunity without having the request rejected, so clearly it's not actually verifying PoP tokens.  In fact, I eliminated the PoP token from my test requests, and it passed through just fine, so I'm going to have to check what's going on there (I thought TAAPSEC was set to require and verify PoP tokens...)

**Comment by klmitch** [comment]
OK, I found another endpoint that _does_ verify PoP tokens, and I have confirmed that my implementation acts correctly.

**Review by komethagan — APPROVED** [review]

**Pull request merged**
